export const MESSAGES = {
  AUTH: {
    LOGIN_SUCCESS: 'Login successful',
    LOGOUT_SUCCESS: 'Logout successful',
    INVALID_CREDENTIALS: 'Invalid username or password',
    TOKEN_EXPIRED: 'Token has expired',
    UNAUTHORIZED: 'You are not authorized to access this resource',
    RESET_LINK_SENT: 'Reset link sent to your email.',
    PASSWORD_CHANGED: 'Password Changed Successfully',
    PASSWORD_VERIFIED: 'Password Verfied Successfully',
    FETCH_SUCCESS: 'User fetched successfully',
    EMAIL_CHANGE_REQUEST: 'Change email request accepted. OTP has been sent to your new email.',
    EMAIL_CHANGED: 'Email Changed Successfully',
    OTP_RESENT: 'Otp Resent Successfully',
    OTP_SENT: 'Otp Sent Successfully',
    OTP_VERIFIED: 'Otp Verfied Successfully',
    TOKEN_REFRESHED: 'Access token refreshed',
  },
  Freelancer: {
    UPDATED: 'Freelancer updated successfully',
    DELETED: 'Freelancer deleted successfully',
    FETCH_SUCCESS: 'Freelancer data fetched successfully',
    NOT_FOUND: 'Freelancer not found',
  },
  CLIENT: {
    UPDATED: 'Client updated successfully',
    DELETED: 'Client deleted successfully',
  },
  USER: {
    NOT_FOUND: 'User not found',
    VERIFIED: 'User Verfied',
    ROLE_SWITCHED: 'Role Switched Successfully',
    ROLE_SELECTED: 'Role Selected Successfully',
    CREATED: 'User created successfully',
    UPDATED: 'User updated successfully',
    FETCH_SUCCESS: 'User data fetched successfully',
    FETCH_STATS_SUCCESS: 'User Stats Fetched Successfully',
    ADDRESS_FETCH_SUCCESS: 'User Address Fetched Successfully',
    ADDRESS_UPDATED: 'User Address Update Successfully',
    PROFILE_UPDATED: 'User Profile Updated Successfully',
    BANK_DETAILS_FETCHED: 'Bank details fetched',
    BANK_DETAILS_SAVED: 'Bank details saved',
    ACTION_VERIFICATION_INITIATED: 'Action verification initiated',
  },
  GENERAL: {
    SERVER_ERROR: 'Something went wrong, please try again later',
    BAD_REQUEST: 'Invalid request',
    FETCH_SUCCESS: 'Data fetched successfully',
  },
  ADMIN: {
    VERIFIED: 'Admin Verified',
  },
  CATEGORY: {
    CREATED: 'Category created successfully',
    UPDATED: 'Category Edited successfully',
    FETCH_SUCCESS: 'Category data fetched successfully',
  },
  SKILL: {
    CREATED: 'Skill created successfully',
    UPDATED: 'Skill Edited successfully',
    FETCH_SUCCESS: 'Skill data fetched successfully',
  },
  SPECIALITY: {
    CREATED: 'Speciality created successfully',
    UPDATED: 'Speciality Edited successfully',
    FETCH_SUCCESS: 'Speciality data fetched successfully',
  },
  JOB: {
    CREATED: 'Job created successfully',
    UPDATED: 'Job Edited successfully',
    FETCH_SUCCESS: 'Job data fetched successfully',
    APPROVE_SUCCESS: 'Job approved successfully',
    REJECT_SUCCESS: 'Job rejected successfully',
    SUSPEND_SUCCESS: 'Job suspended successfully',
    CLOSED: 'Job closed successfully',
    SAVED_FETCH_SUCCESS: 'Saved jobs fetched successfully',
  },
  PROPOSAL: {
    CREATED: 'Proposal created successfully',
    FETCH_SUCCESS: 'Proposal data fetched successfully',
    FETCH_ALL_SUCCESS: 'Proposals fetched successfully',
    FETCH_DETAIL_SUCCESS: 'Proposal detail fetched successfully',
    REJECTED: 'Proposal rejected successfully',
  },
  PORTFOLIO: {
    PORTFOLIO_FETCH_SUCCESS: 'Freelancer portfolio fetched successfully',
    CREATED: 'Portfolio Created',
    DELETED: 'Portfolio Deleted Successfully',
    FETCH_SUCCESS: 'Portfolio Fetched Succcessfully',
  },

  WITHDRAW: {
    FETCH_SUCCESS: 'Withdraw data fetched successfully',
    FETCH_STATS_SUCCESS: 'Withdraw Stats Fetched Successfully',
    APPROVED: 'Withdrawal approved successfully',
    REJECTED: 'Withdrawal rejected successfully',
  },
  REPORT: {
    FETCH_SUCCESS: 'Reports fetched successfully',
    CREATED: 'Report submitted successfully',
  },
  NOTIFICATION: {
    MARKED_AS_READ: 'Notification marked as read',
    ALL_MARKED_AS_READ: 'All notifications marked as read',
  },
  WORKLOG: {
    SUBMITTED: 'Worklog submitted successfully',
    FETCH_SUCCESS: 'Worklogs fetched successfully',
    FETCH_DETAIL_SUCCESS: 'Worklog detail fetched successfully',
    VALIDATION_SUCCESS: 'Worklog validation checked successfully',
  },
  REVIEW: {
    SUBMITTED: 'Review submitted successfully',
    FETCH_SUCCESS: 'Reviews retrieved successfully',
    VISIBILITY_TOGGLED: 'Review visibility toggled successfully',
  },
  OFFER: {
    FETCH_SUCCESS: 'Offers fetched successfully',
    FETCH_DETAIL_SUCCESS: 'Offer detail fetched successfully',
    REJECTED: 'Offer rejected',
    ACCEPTED: 'Offer accepted',
    CREATED: 'Offer created successfully',
    WITHDRAWN: 'Offer withdrawn',
  },
  PAYMENT: {
    INITIATED: 'Payment initiated successfully',
  },
  SAVED_FREELANCER: {
    SAVED: 'Freelancer saved',
    UNSAVED: 'Freelancer unsaved',
    FETCH_SUCCESS: 'Saved freelancers fetched successfully',
  },
  MEETING: {
    FETCH_SUCCESS: 'Meetings fetched successfully',
    FETCH_DETAIL_SUCCESS: 'Meeting detail fetched successfully',
    ACCEPTED: 'Meeting accepted successfully',
    RESCHEDULE_SENT: 'Reschedule request sent successfully',
    REJECTED: 'Meeting rejected successfully',
    PROPOSED: 'Meeting proposed successfully',
    RESCHEDULE_APPROVED: 'Reschedule approved successfully',
    RESCHEDULE_DECLINED: 'Reschedule declined successfully',
    COUNTER_RESCHEDULE_SENT: 'Counter reschedule request sent successfully',
    JOINED: 'Joined meeting successfully',
    PRE_CONTRACT_PROPOSED: 'Pre-contract meeting proposed successfully',
  },
  FINANCE: {
    WITHDRAWAL_REQUEST_CREATED: 'Withdrawal request created',
    HISTORY_FETCHED: 'Withdrawal history fetched',
    DETAIL_FETCHED: 'Withdrawal detail fetched',
    FETCH_SUCCESS: 'Finance data fetched successfully',
  },
  DASHBOARD: {
    FETCH_SUCCESS: 'Dashboard data fetched successfully',
  },
  EARNINGS: {
    OVERVIEW_FETCHED: 'Earnings overview fetched successfully',
    TRANSACTIONS_FETCHED: 'Transactions fetched successfully',
  },
  DISPUTE: {
    CREATED: 'Dispute created successfully',
    FETCH_SUCCESS: 'Dispute fetched successfully',
    FETCH_ALL_SUCCESS: 'Disputes fetched successfully',
    RAISED: 'Dispute raised successfully',
    CONTRACT_CANCELLED_AND_CREATED: 'Contract cancelled and dispute created',
    FUNDS_SPLIT: 'Funds split successfully',
    HOLD_RELEASED: 'Hold released successfully for hourly worklog',
  },
  CHAT: {
    SENT: 'Message sent successfully',
    FETCH_SUCCESS: 'Messages fetched successfully',
    MARKED_AS_READ: 'Messages marked as read',
    UNREAD_COUNT_FETCHED: 'Unread count fetched successfully',
  },
  CONTRACT: {
    FETCH_SUCCESS: 'Contracts fetched successfully',
    FETCH_DETAIL_SUCCESS: 'Contract detail fetched successfully',
    CANCELLATION_PROCESSED: 'Contract cancellation processed',
    DELIVERABLE_SUBMITTED: 'Deliverable submitted successfully',
    MILESTONE_DELIVERABLE_SUBMITTED: 'Milestone deliverable submitted successfully',
    EXTENSION_REQUEST_SUBMITTED: 'Extension request submitted successfully',
    CONTRACT_EXTENSION_REQUEST_SUBMITTED: 'Contract extension request submitted successfully',
    CHANGE_REQUEST_APPROVED: 'Change request approved',
    CANCELLATION_REQUEST_FETCHED: 'Cancellation request fetched successfully',
    CANCELLATION_REQUEST_CREATED: 'Cancellation request created successfully',
    CANCELLED: 'Contract cancelled',
    DELIVERABLE_APPROVED: 'Deliverable approved successfully',
    CHANGES_REQUESTED: 'Changes requested successfully',
    MILESTONE_DELIVERABLE_APPROVED: 'Milestone deliverable approved successfully',
    MILESTONE_CHANGES_REQUESTED: 'Milestone changes requested successfully',
    MILESTONE_DETAIL_FETCHED: 'Milestone detail fetched successfully',
    TIMELINE_FETCHED: 'Contract timeline fetched successfully',
    HOURLY_ACTIVATED: 'Hourly contract activated successfully',
  },
  REPORTED_JOB: {
    REPORTED: 'Report submitted successfully',
    FETCH_SUCCESS: 'Reported job fetched successfully',
  },
  SAVED_JOB: {
    SAVED: 'Job saved',
    UNSAVED: 'Job unsaved',
    FETCH_SUCCESS: 'Saved jobs fetched successfully',
  },
  CONTENT: {
    FETCH_SUCCESS: 'Content fetched successfully',
    UPDATED: 'Content updated successfully',
  },
  FREELANCER_PROFILE: {
    LANGUAGE_DELETED: 'Language Deleted Successfully',
    DESCRIPTION_UPDATED: 'Freelancer Description Update Succcessfully',
    ROLE_UPDATED: 'Freelancer Professional Role Update Succcessfully',
    HOURLY_RATE_UPDATED: 'Freelancer Hourly Rate Update Succcessfully',
    EDUCATION_UPDATED: 'Freelancer Education Update Succcessfully',
    EDUCATION_DELETED: 'Freelancer Education Deleted Succcessfully',
  },
};
