export const DISPUTE_REASONS = {
  WORK_NOT_DELIVERED: 'WORK_NOT_DELIVERED',
  WORK_LOW_QUALITY: 'WORK_LOW_QUALITY',
  DEADLINE_MISSED: 'DEADLINE_MISSED',
  CLIENT_UNRESPONSIVE: 'CLIENT_UNRESPONSIVE',
  FREELANCER_UNRESPONSIVE: 'FREELANCER_UNRESPONSIVE',
  SCOPE_MISMATCH: 'SCOPE_MISMATCH',
  PAYMENT_ISSUE: 'PAYMENT_ISSUE',
  MUTUAL_CANCEL: 'MUTUAL_CANCEL',
  CLIENT_UNFAIR_CANCELLATION:"CLIENT_UNFAIR_CANCELLATION",
  OTHER: 'OTHER',
} as const;

export type DisputeReasonCode = (typeof DISPUTE_REASONS)[keyof typeof DISPUTE_REASONS];
