export const ERROR_MESSAGES = {
  INVALID_ID: 'Invalid ID provided',
  AUTH: {
    EMAIL_ALREADY_EXIST: 'Email already exists',
    ALREADY_EXIST: 'Email or phone number already exists',
    INVALID_CREDENTIALS: 'Invalid username or password',
    TOKEN_EXPIRED: 'Token has expired',
    UNAUTHORIZED: 'You are not authorized to access this resource',
    INCORRECT_PASSWORD: 'Incorrect Password',
    NOT_FOUND: 'Email does not exist',
  },
  CATEGORY: {
    ALREADY_EXIST: 'Category with this name already exists',
  },
  SKILL: {
    ALREADY_EXIST: 'Skill with this name already exists',
    NOT_FOUND: 'Skill not Found',
  },
  SPECIALITY: {
    ALREADY_EXIST: 'Speciality with this name already exists',
  },
  GENERAL: {
    SERVER_ERROR: 'Something went wrong, please try again later',
    BAD_REQUEST: 'Invalid request',
    NOT_FOUND: 'Resource not found',
  },
  TOKEN: {
    INVALID_TOKEN: 'Invalid or Expired Token',
  },
  OTP: {
    EXPIRED: 'OTP has expired',
    INCORRECT_OTP: 'Enter otp is incorrect',
  },
  CLIENT: {
    FAILED_CREATE: 'Failed to create client profile',
    FETCH_FAILED: 'Failed to fetch Client data',
    NOT_FOUND: "Client or Client profile doesn't exist",
  },
  FREELANCER: {
    FAILED_CREATE: 'Failed to create Freelancer profile',
    NOT_FOUND: "Freelancer or Freelancer profile doesn't exist",
    FETCH_FAILED: 'Failed to fetch Freelancer data',
  },
  USER: {
    NOT_FOUND: 'User Not Found',
    ID_REQUIRED: 'User Id Required',
  },
  VALIDATION: {
    FAILED: 'Validation failed',
  },
  PORTFOLIO: {
    NOT_FOUND: 'No Portfolio Found for This Freelancer ID',
  },
  ACTION_VERIFICATION: {
    CHANGE_EMAIL: {
      NOT_FOUND: 'No pending email change request found.',
      PASSWORD_NOT_VERFIED: 'Password Not Verfied',
      OTP_NOT_SENT: 'Otp not sent',
    },
  },
  JOB: {
    NOT_FOUND: 'Job not found',
    INVALID_STATUS: 'Job status is not valid for this operation',
    ALREADY_REPORTED: 'You have already reported this job',
  },
  PROPOSAL: {
    ALREADY_EXIST: 'Proposal already sent',
    NOT_FOUND: 'Proposal Not Found',
  },
  CONTRACT: {
    NOT_FOUND: 'Contract not found',
    UNAUTHORIZED_ACCESS: 'You are not authorized to access this contract',
    MILESTONE_NOT_FOUND: 'Milestone not found',
    MILESTONE_NOT_FUNDED: 'Milestone must be funded to request extension',
    EXTENSION_REQUEST_PENDING: 'An extension request is already pending for this milestone',
    EXTENSION_REQUEST_NOT_FOUND: 'No extension request found for this milestone',
    INVALID_EXTENSION_DATE: 'Extension date must be after current deadline',
    INSUFFICIENT_BALANCE: 'Insufficient balance to cover estimated weekly hours',
    CONTRACT_HELD: 'Contract is on hold due to insufficient balance',
    INVALID_ACTIVATION: 'Cannot activate contract in current status',
    NOT_HOURLY: 'This operation is only valid for hourly contracts',
    ALREADY_CANCELLED: 'Contract is already cancelled',
    INVALID_PAYMENT_TYPE: 'This operation is only valid for fixed payment contracts',
    PENDING_DELIVERABLES: 'Please approve or reject all pending deliverables before cancelling the contract',
    CANCELLATION_IN_PROGRESS: 'Contract cancellation is already in progress',
    INVALID_END_STATUS: 'Contract must be active to be ended',
    PENDING_WORKLOGS: 'Please approve or reject all pending worklogs before ending the contract',
    CANCELLATION_REQUEST_EXISTS: 'A cancellation request already exists for this contract',
    INVALID_SPLIT_PERCENTAGE: 'Split percentages must add up to 100',
    NOT_FUNDED: 'Contract must be funded to create cancellation request',
    NO_DELIVERABLES: 'Cannot create cancellation request without deliverables',
  },
  REVIEW: {
    ALREADY_SUBMITTED: 'You have already submitted a review for this contract',
    CONTRACT_NOT_FOUND: 'Contract not found',
    INVALID_STATUS: 'Contract must be completed or cancelled to submit review',
    INVALID_RATING: 'Rating must be between 1 and 5',
    NOT_FOUND: 'Review not found',
  },
  DISPUTE: {
    NOT_FOUND: 'Dispute not found',
    ALREADY_EXISTS: 'A dispute already exists for this contract',
    INVALID_REASON: 'Invalid dispute reason provided',
    UNAUTHORIZED_ACCESS: 'You are not authorized to access this dispute',
    ALREADY_RESOLVED: 'This dispute has already been resolved',
    CANNOT_RAISE_DISPUTE: 'Cannot raise dispute for this contract in current state',
    INVALID_STATUS: 'Invalid dispute status',
    WORKLOG_NOT_REJECTED: 'Worklog must be rejected to raise a dispute',
    DISPUTE_WINDOW_EXPIRED: 'The dispute window for this worklog has expired',
    WORKLOG_DISPUTE_EXISTS: 'A dispute already exists for this worklog',
    NO_HOLD_TRANSACTION: 'No hold transaction found for this dispute',
    INVALID_SPLIT_PERCENTAGE: 'Client and freelancer percentages must total 100',
    NOT_HOURLY_DISPUTE: 'This operation is only valid for hourly worklog disputes',
  },
  CANCELLATION_REQUEST: {
    NOT_FOUND: 'Cancellation request not found',
    NOT_PENDING: 'Cancellation request is not in pending status',
    ALREADY_RESPONDED: 'You have already responded to this cancellation request',
    UNAUTHORIZED_ACCESS: 'You are not authorized to respond to this cancellation request',
    DISPUTE_ALREADY_RAISED: 'A dispute has already been raised for this cancellation',
  },
  MEETING: {
    NOT_FOUND: 'Meeting not found',
    UNAUTHORIZED: 'You are not authorized to perform this action on this meeting',
    INVALID_STATUS: 'Invalid meeting status for this action',
    REJECT_FAILED: 'Failed to reject meeting',
    UPDATE_FAILED: 'Failed to update meeting',
    SCHEDULED_TIME_REQUIRED: 'Meeting scheduled time is required',
    INVALID_DURATION: 'Duration must be 15, 30, 45, or 60 minutes',
    AGENDA_TOO_SHORT: 'Agenda must be at least 10 characters',
    AGENDA_TOO_LONG: 'Agenda must not exceed 500 characters',
    MUST_BE_FUTURE: 'Meeting must be scheduled in the future',
    ALREADY_ACTIVE: 'An active meeting request already exists for this freelancer',
    TIME_CONFLICT: 'A meeting is already scheduled during this time slot',
    FREELANCER_NOT_FOUND: 'Freelancer not found',
    USER_NOT_FREELANCER: 'User is not a freelancer',
    INVALID_FREELANCER_ID: 'Invalid freelancer ID',
  },
  FINANCE: {
    INSUFFICIENT_BALANCE: 'Insufficient balance for withdrawal',
    INVALID_AMOUNT: 'Invalid withdrawal amount',
  },
  BANK: {
    INVALID_DETAILS: 'Invalid bank details provided',
    NOT_FOUND: 'Bank details not found',
  },
  REPORT: {
    NOT_FOUND: 'No reports found',
  },
  NOTIFICATION: {
    NOT_FOUND: 'Notification not found',
    UNAUTHORIZED: 'You are not authorized to access this notification',
  },
};
